#!/usr/bin/env bash
# Install and setup nginx into the server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "s/listen\s*80;/listen 80 default_server;/g" /etc/nginx/sites-available/default
service nginx start
